version: 2

models:
  - name: customer_stats
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: id
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null

  - name: stg_customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null

  - name: stg_orders
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: status_id
        tests:
          - accepted_values:
              values: [1, 2, 3, 4]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: id
